DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  author TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE posts
ADD COLUMN image_url TEXT;